configuration:
    SERVEUR_IP: "YOUR.SERVER.IP"
    SERVEUR_HOSTNAME: "YOUR.SERVER.HOST"
    SERVEUR_LINK: "LINK.DE.TON.SERVER"
    SERVEUR_PORT: 7002
    SERVEUR_PASSWORD: "YOUR_LINK_PASSWORD"
    SERVEUR_ID: "006"
    SERVEUR_SSL: true
    SERVEUR_PROTOCOL: "unreal6" # unreal6 or inspircd

    SERVICE_NAME: "defender"
    SERVICE_NICKNAME: "PyDefender"
    SERVICE_REALNAME: "Python Defender Security"
    SERVICE_USERNAME: "PyDefender"
    SERVICE_HOST: "HOST.DE.TON.DEFENDER"
    SERVICE_INFO: "Network IRC Service"
    SERVICE_CHANLOG: "#services"
    SERVICE_SMODES: "+ioqBS"
    SERVICE_CMODES: "ntsOP"
    SERVICE_UMODES: "o"
    SERVICE_PREFIX: "!"

    OWNER: "TON_NICK_NAME"
    PASSWORD: "TON_PASSWORD"

    ##########################################
    #    Defender JSON-RPC Configuration     #
    ##########################################
    RPC_HOST: "0.0.0.0"
    RPC_PORT: 5000
    RPC_USERS:
        - USERNAME: "RPC_USER_1"
          PASSWORD: "RPC_USER_1_PASSWORD"
        - USERNAME: "RPC_USER_2"
          PASSWORD: "RPC_USER_2_PASSWORD"

    ##########################################
    #   UnrealIRCD JSON-RPC Configuration    #
    ##########################################
    # unixsocket or http
    JSONRPC_METHOD: "unixsocket"

    # If the method is unixsocket you don't need URL, USER or PASSWORD
    JSONRPC_PATH_TO_SOCKET_FILE: "/PATH/TO/YOUR/IRCD/data/rpc.socket"

    # If METHOD is http
    JSONRPC_URL: "https://your.domaine.com:8600/api"
    JSONRPC_USER: "YOUR_RPC_USER"
    JSONRPC_PASSWORD: "YOUR_RPC_PASSWORD"

    SALON_JAIL: "#jail"
    SALON_JAIL_MODES: "sS"
    SALON_LIBERER: "#welcome"

    CLONE_CHANNEL: "#clones"
    CLONE_CMODES: "+nts"
    CLONE_LOG_HOST_EXEMPT: ["HOST.TO.SKIP"]
    CLONE_CHANNEL_PASSWORD: "YOUR_CHANNEL_PASSWORD"

    API_TIMEOUT: 2

    PORTS_TO_SCAN: [3028, 8080, 1080, 1085, 4145, 9050]
    WHITELISTED_IP: ["127.0.0.1", "192.168.1.1"]
    GLINE_DURATION: "30"

    DEBUG_LEVEL: 20
    DEBUG_HARD: true
